name: Agent 1 - Architect

on:
  issues:
    types: [labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  plan:
    if: github.event.label.name == 'agent-develop'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Check ANTHROPIC_API_KEY exists
        run: |
          if [ -z "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "ERROR: ANTHROPIC_API_KEY secret is not set"
            exit 1
          fi
          echo "API key is configured"
      
      - name: Create Plans
        run: |
          ISSUE_NUM=${{ github.event.issue.number }}
          mkdir -p plans/$ISSUE_NUM
          
          echo "# Architecture Plan" > plans/$ISSUE_NUM/architecture.md
          echo "" >> plans/$ISSUE_NUM/architecture.md
          echo "## Requirements" >> plans/$ISSUE_NUM/architecture.md
          echo "${{ github.event.issue.body }}" >> plans/$ISSUE_NUM/architecture.md
          echo "" >> plans/$ISSUE_NUM/architecture.md
          echo "## System Design" >> plans/$ISSUE_NUM/architecture.md
          echo "- Framework: Express.js" >> plans/$ISSUE_NUM/architecture.md
          echo "- API Endpoint: GET /hello" >> plans/$ISSUE_NUM/architecture.md
          echo "- Response: JSON with message and timestamp" >> plans/$ISSUE_NUM/architecture.md
          
          echo "# Implementation Guide" > plans/$ISSUE_NUM/implementation.md
          echo "" >> plans/$ISSUE_NUM/implementation.md
          echo "## Step 1: Create src/index.js" >> plans/$ISSUE_NUM/implementation.md
          echo "## Step 2: Add Express routes" >> plans/$ISSUE_NUM/implementation.md
          echo "## Step 3: Add tests" >> plans/$ISSUE_NUM/implementation.md
          
          echo "# Test Plan" > plans/$ISSUE_NUM/test-plan.md
          echo "" >> plans/$ISSUE_NUM/test-plan.md
          echo "## Unit Tests" >> plans/$ISSUE_NUM/test-plan.md
          echo "- Test /hello endpoint" >> plans/$ISSUE_NUM/test-plan.md
          echo "- Test response format" >> plans/$ISSUE_NUM/test-plan.md
          
          echo "Plans created successfully"
      
      - name: Commit Plans
        run: |
          ISSUE_NUM=${{ github.event.issue.number }}
          git config user.name "Agent-1-Architect"
          git config user.email "architect@agents.local"
          git checkout -b planning/$ISSUE_NUM
          git add plans/$ISSUE_NUM/
          git commit -m "Architecture plan for issue #$ISSUE_NUM"
          git push origin planning/$ISSUE_NUM
          
      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## 🏗️ Agent 1: Architecture Complete\n\nPlans created in plans/' + issueNumber + '/\n\nNext: Agent 2 will implement.'
            });
          
      - name: Trigger Agent 2
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: agent-2-execute
          client-payload: '{"issue_number": "${{ github.event.issue.number }}"}'
